// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFN-ezwOXKAFBLSHFbtZJEtH1-o_KdwOE',
    appId: '1:253023963463:web:34f9e5dee42d8b60d96462',
    messagingSenderId: '253023963463',
    projectId: 'bazaarshodai-1b01a',
    authDomain: 'bazaarshodai-1b01a.firebaseapp.com',
    storageBucket: 'bazaarshodai-1b01a.firebasestorage.app',
    measurementId: 'G-HLLM4HZFMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDOfKVjb4ayQ8MboP7M9OEhzlqD4rxlM',
    appId: '1:253023963463:android:bc4f96790f75cb44d96462',
    messagingSenderId: '253023963463',
    projectId: 'bazaarshodai-1b01a',
    storageBucket: 'bazaarshodai-1b01a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb4Qf_LViDcr9MkV1f9vLN7qdTAtNjjeo',
    appId: '1:253023963463:ios:c1ae1f8d6d61095bd96462',
    messagingSenderId: '253023963463',
    projectId: 'bazaarshodai-1b01a',
    storageBucket: 'bazaarshodai-1b01a.firebasestorage.app',
    iosBundleId: 'com.bazaarshodai.bazaarShodai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb4Qf_LViDcr9MkV1f9vLN7qdTAtNjjeo',
    appId: '1:253023963463:ios:c1ae1f8d6d61095bd96462',
    messagingSenderId: '253023963463',
    projectId: 'bazaarshodai-1b01a',
    storageBucket: 'bazaarshodai-1b01a.firebasestorage.app',
    iosBundleId: 'com.bazaarshodai.bazaarShodai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFN-ezwOXKAFBLSHFbtZJEtH1-o_KdwOE',
    appId: '1:253023963463:web:bcb8071533c2f79ad96462',
    messagingSenderId: '253023963463',
    projectId: 'bazaarshodai-1b01a',
    authDomain: 'bazaarshodai-1b01a.firebaseapp.com',
    storageBucket: 'bazaarshodai-1b01a.firebasestorage.app',
    measurementId: 'G-YDZMQHN7GZ',
  );
}
